/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import javax.swing.*;

/**
 *
 * @author nicol
 */
public class BookViewingPanel extends javax.swing.JPanel {
    Property property;
    private int month=0;
    private int day=0;
    private int year=0;
    private int hour=0;
    /**
     * Creates new form BookViewingPanel
     */
    public BookViewingPanel(Property property) {
        this.property = property;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dayCombo = new javax.swing.JComboBox<>();
        monthCombo = new javax.swing.JComboBox<>();
        yearCombo = new javax.swing.JComboBox<>();
        hourCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();

        jLabel1.setText("Book a viewing:");

        dayCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dayCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayComboActionPerformed(evt);
            }
        });

        monthCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthComboActionPerformed(evt);
            }
        });

        yearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2021", "2022" }));
        yearCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearComboActionPerformed(evt);
            }
        });

        hourCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hour of visit", "--------------" }));
        hourCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourComboActionPerformed(evt);
            }
        });

        jLabel2.setText("NB : our viewings last around 45 minutes");

        confirmButton.setText("Confirm");
        confirmButton.setEnabled(false);
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hourCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(confirmButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hourCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dayComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayComboActionPerformed
        day = (int)dayCombo.getSelectedIndex();
        updateHours();
    }//GEN-LAST:event_dayComboActionPerformed

    private void monthComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthComboActionPerformed
        month = (int)monthCombo.getSelectedIndex();

        if (month==2||month==4 || month ==6 || month==9|| month ==11){
            dayCombo.removeItem("31");
            if (dayCombo.getItemCount()<31 ){ //if there's not 31 days avalaible
                int initialNrOfDays =dayCombo.getItemCount();
                int daystoadd = 30-dayCombo.getItemCount();
                for (int i=1; i<=daystoadd; i++){
                    dayCombo.addItem(Integer.toString(initialNrOfDays+i));
                }
            }
            if (month==2){
                dayCombo.removeItem("30");
                dayCombo.removeItem("29");
            }
        }
        else { //if it's a month with > than 30 days
            if (dayCombo.getItemCount()<32 ){ //if there's not 31 days avalaible
                int initialNrOfDays =dayCombo.getItemCount();
                int daystoadd = 31-dayCombo.getItemCount();
                for (int i=1; i<=daystoadd; i++){
                    dayCombo.addItem(Integer.toString(initialNrOfDays+i));
                }
            }
        }
        updateHours();
    }//GEN-LAST:event_monthComboActionPerformed

    private void yearComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearComboActionPerformed
        year = Integer.parseInt((String) yearCombo.getSelectedItem());

        updateHours();
    }//GEN-LAST:event_yearComboActionPerformed

    private void hourComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourComboActionPerformed
        String fullHour= (String)hourCombo.getSelectedItem();
        confirmButton.setEnabled(true);
        if (fullHour.charAt(1)=='h'){ //8h / 9h
            hour= Integer.parseInt(String.valueOf(fullHour.charAt(0)));
        }
        else if (fullHour.charAt(2)=='h'){
            String twoDigitsHour= String.valueOf(fullHour.charAt(0)) + String.valueOf(fullHour.charAt(1));
            hour = Integer.parseInt(twoDigitsHour);
        }
        else{
            confirmButton.setEnabled(false);
        }
        
    }//GEN-LAST:event_hourComboActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        if (hourCombo.getSelectedIndex()==0){
            confirmButton.setEnabled(false);
        }
        else{
            BDD.addViewing(property.propertyId,year,month,day,hour);
            String message = "Thank you for your reserving the viewing on the \n"+day+" "+monthCombo.getItemAt(month)+" "+year+", at "+hour+"h for \n"+property.title;
            JOptionPane.showMessageDialog(null, message);
            MainWindow.changePanel(new BrowsePropertiesPanel());
        }
    }//GEN-LAST:event_confirmButtonActionPerformed
    private void updateHours(){
        confirmButton.setEnabled(false);
        for (int i=hourCombo.getItemCount(); i>1; i--){
                hourCombo.removeItemAt(i-1);
        }
        if ((month != 0 && year != 0 && day != 0)){
            
            for (int i=8; i<18;i++){
                if (!BDD.isBooked(property.propertyId,year,month,day,i)){
                    hourCombo.addItem(i+"h -- "+(i+1)+"h");
                }
            }
        }
        confirmButton.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButton;
    private javax.swing.JComboBox<String> dayCombo;
    private javax.swing.JComboBox<String> hourCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> monthCombo;
    private javax.swing.JComboBox<String> yearCombo;
    // End of variables declaration//GEN-END:variables
}
