/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.JToolBar.Separator;

/**
 *https://perso.limsi.fr/vernier/BiSlider/
 * https://perso.limsi.fr/vernier/BiSlider/docs/
 * comparable to http://vernier.frederic.free.fr/BiSlider/stageFV-BISLIDER.html
 * @author Drazic
 */
public class BrowsePropertiesPanelCopy extends JPanel {
    private int minPrice = 0;
    private int maxPrice = 9999999;
    private int minArea = 0;
    private int maxArea = 999999;

    /**
     * Creates new form BrowseProperties
     */
    public BrowsePropertiesPanelCopy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        priceMaxLabel1 = new javax.swing.JLabel();
        priceLabel1 = new javax.swing.JLabel();
        priceMinLabel1 = new javax.swing.JLabel();
        rangeSlider3 = new com.jidesoft.swing.RangeSlider();
        areaMinLabel1 = new javax.swing.JLabel();
        rangeSlider4 = new com.jidesoft.swing.RangeSlider();
        areaMaxLabel1 = new javax.swing.JLabel();
        areaLabel1 = new javax.swing.JLabel();
        backButton21 = new project.BackButton2();
        jScrollPane1 = new javax.swing.JScrollPane();
        container = new javax.swing.JPanel();

        jLabel1.setText("Browse Properties");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        priceMaxLabel1.setText("2,000,000 €");

        priceLabel1.setText("Price");

        priceMinLabel1.setText("0 €");

        rangeSlider3.setMajorTickSpacing(25000);
        rangeSlider3.setMaximum(2000000);
        rangeSlider3.setSnapToTicks(true);
        rangeSlider3.setExtent(2500000);
        rangeSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rangeSlider1StateChanged(evt);
            }
        });

        areaMinLabel1.setText("0 m²");

        rangeSlider4.setMajorTickSpacing(10);
        rangeSlider4.setMaximum(500);
        rangeSlider4.setSnapToTicks(true);
        rangeSlider4.setLowValue(0);
        rangeSlider4.setName(""); // NOI18N
        rangeSlider4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rangeSlider2StateChanged(evt);
            }
        });

        areaMaxLabel1.setText("500 m²");

        areaLabel1.setText("Area");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(priceLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(areaLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rangeSlider4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rangeSlider3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(priceMinLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(priceMaxLabel1))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(areaMinLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(areaMaxLabel1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(priceLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rangeSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceMinLabel1)
                    .addComponent(priceMaxLabel1))
                .addGap(0, 0, 0)
                .addComponent(areaLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rangeSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areaMinLabel1)
                    .addComponent(areaMaxLabel1)))
        );

        rangeSlider4.getAccessibleContext().setAccessibleName("");

        container.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        container.setMaximumSize(new java.awt.Dimension(300, 300));
        container.setLayout(new javax.swing.BoxLayout(container, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addComponent(backButton21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 274, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rangeSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rangeSlider2StateChanged
        // TODO add your handling code here:
        minArea = rangeSlider4.getLowValue();
        maxArea = rangeSlider4.getHighValue();
        
        String min_txt = Integer.toString(rangeSlider4.getLowValue());
        String max_txt = Integer.toString(rangeSlider4.getHighValue());
        areaMinLabel.setText(min_txt+" m²");
        areaMaxLabel.setText(max_txt+" m²");
        
        loadPropertiesFilter();
    }//GEN-LAST:event_rangeSlider2StateChanged

    private void rangeSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rangeSlider1StateChanged
        // TODO add your handling code here:
        minPrice = rangeSlider3.getLowValue();
        maxPrice = rangeSlider3.getHighValue();
        
        Locale locale  = new Locale("en", "UK");
        String pattern = "###,###,###";

        DecimalFormat decimalFormat = (DecimalFormat)
        NumberFormat.getNumberInstance(locale);
        decimalFormat.applyPattern(pattern);

        String formatmax = decimalFormat.format(rangeSlider3.getHighValue());
        String formatmin = decimalFormat.format(rangeSlider3.getLowValue());
        priceMinLabel.setText(formatmin+" €");
        priceMaxLabel.setText(formatmax+" €");
        
        loadPropertiesFilter();
    }//GEN-LAST:event_rangeSlider1StateChanged
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areaLabel;
    private javax.swing.JLabel areaLabel1;
    private javax.swing.JLabel areaMaxLabel;
    private javax.swing.JLabel areaMaxLabel1;
    private javax.swing.JLabel areaMinLabel;
    private javax.swing.JLabel areaMinLabel1;
    private project.BackButton2 backButton21;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceLabel1;
    private javax.swing.JLabel priceMaxLabel;
    private javax.swing.JLabel priceMaxLabel1;
    private javax.swing.JLabel priceMinLabel;
    private javax.swing.JLabel priceMinLabel1;
    private com.jidesoft.swing.RangeSlider rangeSlider1;
    private com.jidesoft.swing.RangeSlider rangeSlider2;
    private com.jidesoft.swing.RangeSlider rangeSlider3;
    private com.jidesoft.swing.RangeSlider rangeSlider4;
    // End of variables declaration//GEN-END:variables
    
    private void loadAllProperties() {
        try {
            PreparedStatement st;
            ResultSet rs;
            
            String query = "SELECT * FROM property";
            
            st = BDD.getConnection().prepareStatement(query);
            
            rs = st.executeQuery();
            
            while(rs.next()){
                System.out.println(rs.getString("title"));
                
                Property p = Property.getPropertyFromRS(rs);
                
                if (p != null){
                    PropertyScroolPaneElement2 newpPropertyScroolPaneElement = new PropertyScroolPaneElement2(p);
                    container.add(newpPropertyScroolPaneElement);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(BDD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void loadPropertiesFilter(){
        try {
            ResultSet rs = BDD.propertiesFilter(minPrice, maxPrice, minArea, maxArea);
            if (rs == null) return;
            
            container.removeAll();
            
            while(rs.next()){
                Property p = Property.getPropertyFromRS(rs);
                
                if (p != null){
                    PropertyScroolPaneElement2 newpPropertyScroolPaneElement = new PropertyScroolPaneElement2(p);
                    container.add(newpPropertyScroolPaneElement);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(BrowsePropertiesPanelCopy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
