/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Dimension;
import java.awt.Font;
import static project.Tokeniser.Token.BUYER;
import static project.Tokeniser.Token.EMPLOYEE;
import static project.Tokeniser.Token.SELLER;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Drazic
 */
public class PropertyPanel extends javax.swing.JPanel {
    Property property;
    private int month=0;
    private int day=0;
    private int year=0;
    private int hour=0;
   
    /**
     * Creates new form propertyPanel
     */
    public PropertyPanel() {
        initComponents();
        
    }
    
    public PropertyPanel(Property property) {
        this.property = property;
        initComponents();
        desciptionText.setText(property.description);
        desciptionText.setLineWrap(true);
        desciptionText.setWrapStyleWord(true);
        
        
        
        if (MainWindow.getUser().token==BUYER){
            if (BDD.hasBuyerAlreadyReservedViewing(MainWindow.getUser().getUserId() , property.getPropertyId())){
                ResultSet rs = BDD.getOneViewing(MainWindow.getUser().getUserId(), property.getPropertyId());
                if (rs != null){
                    try {
                        if (rs.next()){
                            viewingPanel.add(new JLabel("You have already reserved a viewing :"));
                            viewingPanel.add(Box.createRigidArea(new Dimension(10, 0)));
                            viewingPanel.add(new ViewingPanelElement(property, rs.getInt("year"), rs.getInt("month"), rs.getInt("day"), rs.getInt("hour"),rs.getInt("price"),rs.getString("title"),rs.getDouble("area")));
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(PropertyPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
            }else{
                viewingPanel.add(new BookViewingPanel(property));
            }
            if (BDD.isWithOffer(property.getPropertyId(), MainWindow.getUser().getUserId())){
                ResultSet rs = BDD.getOffer(property.getPropertyId(), MainWindow.getUser().getUserId());
                if (rs!=null) {
                    try {
                        if (rs.next()){
                            
                            Offer myOffer = Offer.getOfferFromRS(rs);
                            
                            offerPanel.add(new SendOfferPanel(property, myOffer));
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(PropertyPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
        
        loaddata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        areaLabel = new javax.swing.JLabel();
        backButton1 = new project.BackButton2();
        favCheckBox = new javax.swing.JCheckBox();
        viewingPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desciptionText = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        setSellButton = new javax.swing.JButton();
        editPropertyButton = new javax.swing.JButton();
        sendOfferButton = new javax.swing.JButton();
        offerPanel = new javax.swing.JPanel();

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        titleLabel.setText("titleLabel");

        addressLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        addressLabel.setText("address");

        priceLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        priceLabel.setText("price");

        areaLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        areaLabel.setText("area");

        favCheckBox.setText("add to Favorites");
        favCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favCheckBoxActionPerformed(evt);
            }
        });

        viewingPanel.setLayout(new javax.swing.BoxLayout(viewingPanel, javax.swing.BoxLayout.X_AXIS));

        desciptionText.setEditable(false);
        desciptionText.setBackground(new java.awt.Color(240, 240, 240));
        desciptionText.setColumns(20);
        desciptionText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        desciptionText.setRows(5);
        jScrollPane1.setViewportView(desciptionText);

        jButton1.setText("Back to properties");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setSellButton.setText("Set it as selled");
        setSellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setSellButtonActionPerformed(evt);
            }
        });

        editPropertyButton.setText("Edit Property");
        editPropertyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPropertyButtonActionPerformed(evt);
            }
        });

        sendOfferButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sendOfferButton.setText(" Send offer ");
        sendOfferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendOfferButtonActionPerformed(evt);
            }
        });

        offerPanel.setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(priceLabel)
                            .addComponent(addressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(areaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(setSellButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editPropertyButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(backButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(offerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(favCheckBox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sendOfferButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel)
                    .addComponent(backButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(favCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areaLabel)
                    .addComponent(editPropertyButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(setSellButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendOfferButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(offerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void favCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favCheckBoxActionPerformed
        // TODO add your handling code here:
        if (favCheckBox.isSelected()){
            BDD.setFav(property.propertyId, MainWindow.getUser().userId);
        }else{
            BDD.deleteFav(property.propertyId, MainWindow.getUser().userId);
        }
    }//GEN-LAST:event_favCheckBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainWindow.changePanel(new BrowsePropertiesPanel());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void setSellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setSellButtonActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(this, 
                "Set selled this properties : "+property.getTitle(), "Confirmation dialogue", 
                JOptionPane.YES_NO_OPTION, JOptionPane.YES_NO_CANCEL_OPTION);
        
        if (input == 0){
            // yes
            BDD.setPropertySelled(property.getPropertyId());
            MainWindow.changePanel(new BrowsePropertiesPanel());
        }
    }//GEN-LAST:event_setSellButtonActionPerformed

    private void editPropertyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPropertyButtonActionPerformed
        AddPropertyPopUp2.main(property);
    }//GEN-LAST:event_editPropertyButtonActionPerformed

    private void sendOfferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendOfferButtonActionPerformed
        int offer = Integer.parseInt(JOptionPane.showInputDialog(null, "Send an offer", property.getPrice()));
        BDD.addOffer(property.getPropertyId(), MainWindow.getUser().getUserId(), offer);
        JOptionPane.showMessageDialog(null, "You have successfully sent the offer for \n"+property.getTitle()+" for "+Integer.toString(offer)+" €");
    }//GEN-LAST:event_sendOfferButtonActionPerformed
    
    private void loaddata() {
        
        sendOfferButton.setVisible(false);
        if (MainWindow.getUser().token == SELLER || MainWindow.getUser().token == EMPLOYEE){
            favCheckBox.setVisible(false);
        }else{
            sendOfferButton.setVisible(true);
            //if(BDD.isWithOffer(property.getPropertyId(),MainWindow.getUser().getUserId())){
            //    sendOfferButton.setEnabled(false);
            //}
            if (BDD.isFav(property.getPropertyId(), MainWindow.getUser().getUserId())){
            favCheckBox.setSelected(true);
            }else{
                favCheckBox.setSelected(false);
            }
        }
        
        setSellButton.setVisible(false);
        editPropertyButton.setVisible(false);
        if (MainWindow.getUser().getToken() == EMPLOYEE || BDD.canSetSellProperty(MainWindow.getUser().getUserId(), property.getPropertyId())){
            setSellButton.setVisible(true);
            editPropertyButton.setVisible(true);
        }
        
        titleLabel.setText(property.getTitle());
        addressLabel.setText(property.getAddress());
        areaLabel.setText("Area : "+property.getArea()+"m²");
        priceLabel.setText("Price : "+property.getPrice()+"€");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel areaLabel;
    private project.BackButton2 backButton1;
    private javax.swing.JTextArea desciptionText;
    private javax.swing.JButton editPropertyButton;
    private javax.swing.JCheckBox favCheckBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel offerPanel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JButton sendOfferButton;
    private javax.swing.JButton setSellButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel viewingPanel;
    // End of variables declaration//GEN-END:variables
}
