/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author Drazic
 */
public class PropertyScroolPaneElement2 extends javax.swing.JPanel {
    Property property;
    /**
     * Creates new form propertyScroolPanelElement
     * @param 
     */
    public PropertyScroolPaneElement2(Property p) {
        this.property = p;
        initComponents();
        
        titleLabel.setText(property.getTitle());
        addressLabel.setText(property.getAddress());
        areaLabel.setText("Area : "+property.getArea()+"m²");
        priceLabel.setText("Price : "+property.getPrice()+"€");
        
        loaddata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        favRadioButton = new javax.swing.JRadioButton();
        areaLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 100));

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titleLabel.setText("titleLabel");

        addressLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        addressLabel.setText("addressLabel");

        favRadioButton.setText("Fav");
        favRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favRadioButtonActionPerformed(evt);
            }
        });

        areaLabel.setText("area");

        priceLabel.setText("price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(areaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(favRadioButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(areaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
            .addComponent(favRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(priceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void favRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favRadioButtonActionPerformed
        // TODO add your handling code here:
        if (favRadioButton.isSelected()){
            // add fav
            BDD.setFav(property.getPropertyId(),MainWindow.getUser().getUserId());
        }else{
            // delete fav
            BDD.deleteFav(property.getPropertyId(),MainWindow.getUser().getUserId());
        }
    }//GEN-LAST:event_favRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel areaLabel;
    private javax.swing.JRadioButton favRadioButton;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    private void loaddata() {
        if (BDD.isFav(property.getPropertyId(), MainWindow.getUser().getUserId())){
            favRadioButton.setSelected(true);
        }else{
            favRadioButton.setSelected(false);
        }
    }
}
