/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Drazic
 */
public class ViewingPanelElement extends javax.swing.JPanel {
    private int day;
    private int month;
    private int year;
    private int hour;
    private int price;
    private String title;
    private double area;
    private Property property;
    private boolean fromBrowse=false;
    /**
     * Creates new form ViewingPanelElement
     */
    public ViewingPanelElement(Property property, int year, int month, int day, int hour, int price, String title, double area) {
        this.property = property;
        this.year = year;
        this.month = month;
        this.day = day;
        this.hour = hour;
        this.area = area;
        this.title = title;
        this.price = price;
        initComponents();
        //if (withdraw == true){
        //    cancelViewing.setVisible(true);
        //}
        loaddata();
    }

    public void setFromBrowse(boolean fromBrowse) {
        this.fromBrowse = fromBrowse;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        areaLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        hourLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        cancelViewing = new javax.swing.JButton();

        setBackground(new java.awt.Color(197, 217, 217));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        titleLabel.setText("Title");

        areaLabel.setText("area");

        priceLabel.setText("price");

        hourLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        hourLabel.setForeground(new java.awt.Color(204, 0, 51));
        hourLabel.setText("hourStart");

        dateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(204, 0, 51));
        dateLabel.setText("date :");

        cancelViewing.setText("Withdraw");
        cancelViewing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelViewingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(areaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hourLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(priceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(cancelViewing)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelViewing)
                    .addComponent(titleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hourLabel)
                    .addComponent(areaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(priceLabel)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        MainWindow.changePanel(new PropertyPanel(property));
    }//GEN-LAST:event_formMouseClicked

    private void cancelViewingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelViewingActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog (null, "Are you sure you want to delete this viewing?");
        if(dialogResult == JOptionPane.YES_OPTION){
            BDD.deleteViewing(property.getPropertyId(), MainWindow.getUser().getUserId());
            if(fromBrowse){
                MainWindow.changePanel(new ViewingPanel());
            }
            else{
                MainWindow.changePanel(new PropertyPanel(property));
            }
        }
        
        
    }//GEN-LAST:event_cancelViewingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areaLabel;
    private javax.swing.JButton cancelViewing;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel hourLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    private void loaddata() {
        String date = String.format("Date : %02d/%02d/%02d",day,month,year);
        dateLabel.setText(date);
        hourLabel.setText(Integer.toString(hour)+"h - "+Integer.toString(hour+1)+"h ");
        
        Locale locale  = new Locale("en", "UK");
        String pattern = "###,###,###";

        DecimalFormat decimalFormat = (DecimalFormat)
        NumberFormat.getNumberInstance(locale);
        decimalFormat.applyPattern(pattern);
        
        String priceTemp = decimalFormat.format(price);
        priceLabel.setText(priceTemp+"€");
        areaLabel.setText("Area : "+area+" m²");
        titleLabel.setText(title);
    }
}
